name: Monthly Report

on:
  schedule:
    - cron: "0 0 1 * *" # Runs on the first of every month
  workflow_dispatch: # Allows manual triggering

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate issue content
        id: generate-content
        run: |
          CURRENT_MONTH=$(date +"%Y-%m")
          LAST_MONTH=$(date -d "-1 month" +"%Y-%m")
          echo "CURRENT_MONTH=$CURRENT_MONTH" >> $GITHUB_ENV
          echo "LAST_MONTH=$LAST_MONTH" >> $GITHUB_ENV

          node admin-scripts/generate-monthly-report.js > monthly_report.md
        env:
          CURRENT_MONTH: ${{ env.CURRENT_MONTH }}
          LAST_MONTH: ${{ env.LAST_MONTH }}

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Monthly Report for ${{ env.CURRENT_MONTH }}"
          content-filepath: monthly_report.md
          labels: report

      - name: Find last month's report issue
        id: find-issue
        run: |
          number=$(gh issue list --search "Monthly Report for ${{ env.LAST_MONTH }}" --json number,title --jq '.[0].number')
          echo "issue-number=$number" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close last month's issue
        if: steps.find-issue.outputs.issue-number != ''
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.find-issue.outputs.issue-number }}
          comment: "Automatically closing last month's report."
